services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=escola
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  api-avaliacao:
    build: .
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - api-network
    ports:
      - ${SERVER_PORT}:8080
volumes:
  app-data:
networks:
  api-network:
