services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
    env_file:
      - .env
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - app-data:/var/lib/pgsql/data
    networks:
      - api-network
  api-avaliacao:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - api-network
    ports:
      - ${SERVER_PORT}:8080
volumes:
  app-data:
networks:
  api-network: